### ISSUE TITLE
Aantal knop met plus en min

### ISSUE THREAD

**Issue by Pridestalker** [DoedeJaarsmaCommunicatie/littlefinger#18]
Op een productpagina is het makkelijker als je een `-` en een `+` knop krijgt voor het verhogen van het aantal wat je toe wil voegen.

**Comment by Pridestalker** [comment]
Toevoegen:
```css
.product .product-form #quantity {
  appearance: textfield;
}
```
